org: aska03537
app: aws-feedback-project
service: aws-feedback-project
frameworkVersion: '3'

custom:
  serverless-offline:
    noPrependStageInUrl: true
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  dotenv:
    dotenvVars: ${file(config.js)}

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"
  environment:
    USERS_TABLE: UsersTable
    FEEDBACKS_TABLE: FeedbacksTable
    STATUSES_TABLE: StatusesTable
    TYPES_TABLE: TypesTable
    COMMENTS_TABLE: CommentsTable


functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: UsersTable
        GlobalSecondaryIndexes:
          - IndexName: UserByEmail
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    FeedbacksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: typeId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: FeedbacksTable
        GlobalSecondaryIndexes:
          - IndexName: FeedbackByTypeId
            KeySchema:
              - AttributeName: typeId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    StatusesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: StatusesTable
    TypesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: TypesTable
    CommentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: CommentsTable

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-tables
  - serverless-dynamodb-local
  - serverless-offline
